Repository NOWSOPT-CDSP-WEB-1/Brunch-Web-Server, pull requests merged in 2024-05, with the labels that each got.

#3 [INIT] 개발 초기 세팅
  src/main/java/com/brunch/server/author/entity/Author.java
  src/main/java/com/brunch/server/author/message/ErrorMessage.java
  src/main/java/com/brunch/server/author/message/SuccessMessage.java
  src/main/java/com/brunch/server/author/repository/AuthorRepository.java
  src/main/java/com/brunch/server/book/controller/BookController.java
  src/main/java/com/brunch/server/book/entity/Book.java
  src/main/java/com/brunch/server/book/exception/BookException.java
  src/main/java/com/brunch/server/book/message/ErrorMessage.java
  src/main/java/com/brunch/server/book/message/SuccessMessage.java
  src/main/java/com/brunch/server/book/repository/BookRepository.java
  src/main/java/com/brunch/server/book/service/BookService.java
  src/main/java/com/brunch/server/common/dto/BaseResponse.java
  src/main/java/com/brunch/server/common/dto/ErrorResponse.java
  src/main/java/com/brunch/server/common/dto/SuccessResponse.java
  src/main/java/com/brunch/server/common/handler/ErrorHandler.java
  src/main/java/com/brunch/server/posting/controller/PostingController.java
  src/main/java/com/brunch/server/posting/dto/response/PostingResponse.java
  src/main/java/com/brunch/server/posting/dto/response/ViewedPostingResponse.java
  src/main/java/com/brunch/server/posting/entity/Posting.java
  src/main/java/com/brunch/server/posting/exception/PostingException.java
  src/main/java/com/brunch/server/posting/message/ErrorMessage.java
  src/main/java/com/brunch/server/posting/message/SuccessMessage.java
  src/main/java/com/brunch/server/posting/repository/PostingRepository.java
  src/main/java/com/brunch/server/posting/service/PostingService.java
  src/main/resources/application-dev.yml
Labels: setting

#14 [FEAT] 책 조회 API 구현
  .gitignore
  src/main/java/com/brunch/server/author/entity/Author.java
  src/main/java/com/brunch/server/author/exeception/AuthorException.java
  src/main/java/com/brunch/server/author/message/ErrorMessage.java
  src/main/java/com/brunch/server/book/controller/BookController.java
  src/main/java/com/brunch/server/book/entity/Book.java
  src/main/java/com/brunch/server/book/message/ErrorMessage.java
  src/main/java/com/brunch/server/book/message/SuccessMessage.java
  src/main/java/com/brunch/server/book/repository/BookRepository.java
  src/main/java/com/brunch/server/book/service/BookService.java
  src/main/java/com/brunch/server/book/service/BookServiceImpl.java
  src/main/java/com/brunch/server/book/service/dto/BannerResponse.java
  src/main/java/com/brunch/server/book/service/dto/BookChapterResponse.java
  src/main/java/com/brunch/server/book/service/dto/BookDetailResponse.java
  src/main/java/com/brunch/server/book/service/dto/BookLikeResponse.java
  src/main/java/com/brunch/server/book/service/dto/BookOverviewResponse.java
  src/main/java/com/brunch/server/book/service/dto/LikedBookResponse.java
  src/main/java/com/brunch/server/book/service/dto/RecentBookResponse.java
  src/main/java/com/brunch/server/book/service/dto/RecentLikedResponse.java
  src/main/resources/application-local.yml
Labels: feature

#21 [FIX] 요일별 글 목록 조회 api
  src/main/java/com/brunch/server/posting/dto/response/SerializedPostingsResponse.java
  src/main/java/com/brunch/server/posting/repository/PostingRepository.java
  src/main/java/com/brunch/server/posting/service/PostingService.java
Labels: feature, fix

#24 [FEAT] 추천 글 목록 조회 api
  src/main/java/com/brunch/server/posting/controller/PostingController.java
  src/main/java/com/brunch/server/posting/dto/response/RecommendedPostingResponse.java
  src/main/java/com/brunch/server/posting/message/SuccessMessage.java
  src/main/java/com/brunch/server/posting/repository/PostingRepository.java
  src/main/java/com/brunch/server/posting/service/PostingService.java
Labels: feature
